from enum import Enum


class PortfolioDataHeader(str, Enum):
    DATE = "date"
    P_TICKER = "p_ticker"
    SHORT_NAME = "short_name"
    OPENING_WEIGHTS = "opening_weights"
    OPEN_QUANTITY = "open_quantity"
    CLOSE_QUANTITY = "close_quantity"
    CLOSING_WEIGHTS = "closing_weights"
    CURRENCY = "currency"
    PRICE = "price"
    EXCHANGE_RATE = "exchange_rate"
    VALUE_IN_USD = "value_in_usd"
    PRICE_YESTERDAY = "price_yesterday"
    STOCK_MOVEMENT = "stock_movement"
    PERFORMANCE_CONTRIBUTION = "performance_contribution"
    TRADED_TODAY = "traded_today"
    TRADE_PRICE = "trade_price"
    TRADE_DAY_MOVE = "trade_day_move"
    TRADE_WEIGHT = "trade_weight"
    RETURN_ADJUSTMENTS = "return_adjustments"
    TOTAL_RETURN = "total_return"
    CALCULATED_NAV = "calculated_nav"
    NAV_YESTERDAY = "nav_yesterday"
    COUNTRY = "country"
    SECTOR = "sector"
    INDUSTRY = "industry"
    SUB_IND = "sub_ind"
    IS_CURRENCY = "is_currency"
    CLOSE_WEIGHT_ABS = "close_weight_abs"
    IS_FUTURE = "is_future"
    SHORT_POS = "short_pos"
    DOLLAR_PNL = "dollar_pnl"
    SHARESOUT = "sharesout"
    MARKET_CAP = "market_cap"
    CAP_CLASS = "cap_class"
